package org.example.tas_backend.controllers;

import org.example.tas_backend.dtos.OcrResponse;
import org.example.tas_backend.entities.Application;
import org.example.tas_backend.entities.StudentApplicant;
import org.example.tas_backend.enums.ApplicationStatus;
import org.example.tas_backend.repos.ApplicationRepo;
import org.example.tas_backend.repos.StudentApplicantRepo;
import org.example.tas_backend.services.AiService;
import org.example.tas_backend.services.AcceptanceService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.multipart;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "storage.upload-root=${java.io.tmpdir}/it-uploads",
        "ai.ocr-url=http://mock-ocr"
})
@AutoConfigureMockMvc
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:tas_it;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR",
        "spring.datasource.driverClassName=org.h2.Driver",
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.jpa.properties.hibernate.envers.autoRegisterListeners=false",
        "spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop"
})
class StudentApplicationIntegrationTests {

    @Autowired
    private MockMvc mockMvc;
    @Autowired
    private StudentApplicantRepo studentApplicantRepo;
    @Autowired
    private ApplicationRepo applicationRepo;
    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockBean
    private AiService aiService;
    @MockBean
    private RestTemplate restTemplate;
    @MockBean
    private AcceptanceService acceptanceService;

    private static final String STUDENT_SUB = "student-sub";

    @BeforeEach
    void setup() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS extracted_subject (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                document_id BIGINT,
                raw_name VARCHAR(255),
                raw_score REAL,
                raw_scale VARCHAR(255),
                \"year\" INT,
                source_coefficient REAL,
                created_at TIMESTAMP,
                created_by VARCHAR(255),
                updated_at TIMESTAMP,
                updated_by VARCHAR(255)
            )
            """);
        applicationRepo.deleteAll();
        studentApplicantRepo.deleteAll();
        StudentApplicant student = new StudentApplicant();
        student.setKeycloakSub(STUDENT_SUB);
        studentApplicantRepo.save(student);

        when(restTemplate.postForEntity(eq("http://mock-ocr"), any(), eq(OcrResponse.class)))
                .thenReturn(org.springframework.http.ResponseEntity.ok(new OcrResponse("file.pdf", "Advanced Algebra", 1, List.of("Advanced Algebra"))));
        when(aiService.matchSubjects(anyList(), anyList()))
                .thenReturn(null);
    }

    @Test
    void postApplyPersistsApplicationAndInvokesAi() throws Exception {
        MockMultipartFile jsonPart = new MockMultipartFile(
                "data", "data", "application/json",
                """
                {"preferredProgram":"Data Science","languageLevel":"B2","profile":null}
                """.getBytes()
        );
        MockMultipartFile filePart = new MockMultipartFile(
                "files", "transcript.pdf", MediaType.APPLICATION_PDF_VALUE, "dummy".getBytes()
        );

        mockMvc.perform(multipart("/student/apply")
                        .file(jsonPart)
                        .file(filePart)
                        .with(jwt().jwt(jwt -> jwt.subject(STUDENT_SUB)
                                .claim("realm_access", Map.of("roles", List.of("student")))
                                .claim("aud", List.of("angular"))
                                .issuer("http://localhost:8080/realms/TAS"))
                                .authorities(t -> java.util.List.of(new org.springframework.security.core.authority.SimpleGrantedAuthority("ROLE_STUDENT")))))
                .andExpect(status().is2xxSuccessful());

        List<Application> apps = applicationRepo.findAll();
        assertThat(apps).hasSize(1);
        assertThat(apps.get(0).getStatus()).isEqualTo(ApplicationStatus.SUBMITTED);

        verify(aiService, times(1)).matchSubjects(anyList(), anyList());
    }
}
